/*
 * langfuse
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kuga.langfuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateDatasetRunItemRequest
 */
public class CreateDatasetRunItemRequestTest {
    private final CreateDatasetRunItemRequest model = new CreateDatasetRunItemRequest();

    /**
     * Model tests for CreateDatasetRunItemRequest
     */
    @Test
    public void testCreateDatasetRunItemRequest() {
        // TODO: test CreateDatasetRunItemRequest
    }

    /**
     * Test the property 'runName'
     */
    @Test
    public void runNameTest() {
        // TODO: test runName
    }

    /**
     * Test the property 'runDescription'
     */
    @Test
    public void runDescriptionTest() {
        // TODO: test runDescription
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'datasetItemId'
     */
    @Test
    public void datasetItemIdTest() {
        // TODO: test datasetItemId
    }

    /**
     * Test the property 'observationId'
     */
    @Test
    public void observationIdTest() {
        // TODO: test observationId
    }

    /**
     * Test the property 'traceId'
     */
    @Test
    public void traceIdTest() {
        // TODO: test traceId
    }

}
