/*
 * langfuse
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kuga.langfuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kuga.langfuse.client.model.DatasetStatus;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DatasetItem
 */
public class DatasetItemTest {
    private final DatasetItem model = new DatasetItem();

    /**
     * Model tests for DatasetItem
     */
    @Test
    public void testDatasetItem() {
        // TODO: test DatasetItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'input'
     */
    @Test
    public void inputTest() {
        // TODO: test input
    }

    /**
     * Test the property 'expectedOutput'
     */
    @Test
    public void expectedOutputTest() {
        // TODO: test expectedOutput
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'sourceTraceId'
     */
    @Test
    public void sourceTraceIdTest() {
        // TODO: test sourceTraceId
    }

    /**
     * Test the property 'sourceObservationId'
     */
    @Test
    public void sourceObservationIdTest() {
        // TODO: test sourceObservationId
    }

    /**
     * Test the property 'datasetId'
     */
    @Test
    public void datasetIdTest() {
        // TODO: test datasetId
    }

    /**
     * Test the property 'datasetName'
     */
    @Test
    public void datasetNameTest() {
        // TODO: test datasetName
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
