/*
 * langfuse
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kuga.langfuse.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UsageByModel
 */
public class UsageByModelTest {
    private final UsageByModel model = new UsageByModel();

    /**
     * Model tests for UsageByModel
     */
    @Test
    public void testUsageByModel() {
        // TODO: test UsageByModel
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'inputUsage'
     */
    @Test
    public void inputUsageTest() {
        // TODO: test inputUsage
    }

    /**
     * Test the property 'outputUsage'
     */
    @Test
    public void outputUsageTest() {
        // TODO: test outputUsage
    }

    /**
     * Test the property 'totalUsage'
     */
    @Test
    public void totalUsageTest() {
        // TODO: test totalUsage
    }

    /**
     * Test the property 'countTraces'
     */
    @Test
    public void countTracesTest() {
        // TODO: test countTraces
    }

    /**
     * Test the property 'countObservations'
     */
    @Test
    public void countObservationsTest() {
        // TODO: test countObservations
    }

    /**
     * Test the property 'totalCost'
     */
    @Test
    public void totalCostTest() {
        // TODO: test totalCost
    }

}
