/*
 * langfuse
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kuga.langfuse.client.invoker;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.BaseEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.BasePrompt.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.BaseScore.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.BooleanScore.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CategoricalScore.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ChatMessage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ChatPrompt.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ConfigCategory.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateChatPromptRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateDatasetItemRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateDatasetRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateDatasetRunItemRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateEventBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateEventEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateGenerationBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateGenerationEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateModelRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateObservationEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreatePromptRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreatePromptRequestOneOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreatePromptRequestOneOf1.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateScoreConfigRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateScoreRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateScoreResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateScoreValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateSpanBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateSpanEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.CreateTextPromptRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.DailyMetrics.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.DailyMetricsDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Dataset.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.DatasetItem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.DatasetRun.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.DatasetRunItem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.DatasetRunWithItems.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.HealthResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionBatchRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionEventOneOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionEventOneOf1.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionEventOneOf2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionEventOneOf3.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionEventOneOf4.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionEventOneOf5.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionEventOneOf6.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionEventOneOf7.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionEventOneOf8.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionEventOneOf9.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionSuccess.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.IngestionUsage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.MapValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Model.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.NumericScore.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Observation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ObservationBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Observations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ObservationsView.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ObservationsViews.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.OpenAIUsage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.OptionalObservationBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.PaginatedDatasetItems.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.PaginatedDatasetRuns.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.PaginatedDatasets.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.PaginatedModels.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.PaginatedSessions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Project.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Projects.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Prompt.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.PromptMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.PromptMetaListResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.PromptOneOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.PromptOneOf1.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.SDKLogBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.SDKLogEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Score.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ScoreBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ScoreConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ScoreConfigs.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ScoreEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ScoreOneOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ScoreOneOf1.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.ScoreOneOf2.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Scores.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Session.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.SessionWithTraces.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Sort.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.TextPrompt.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Trace.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.TraceBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.TraceEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.TraceWithDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.TraceWithFullDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Traces.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.UpdateEventBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.UpdateGenerationBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.UpdateGenerationEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.UpdateObservationEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.UpdateSpanBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.UpdateSpanEvent.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.Usage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.UsageByModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.kuga.langfuse.client.model.UtilsMetaResponse.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
