/*
 * langfuse
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kuga.langfuse.client.api;

import com.kuga.langfuse.client.invoker.ApiException;
import com.kuga.langfuse.client.model.CreateDatasetRunItemRequest;
import com.kuga.langfuse.client.model.DatasetRunItem;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DatasetRunItemsApi
 */
@Disabled
public class DatasetRunItemsApiTest {

    private final DatasetRunItemsApi api = new DatasetRunItemsApi();

    /**
     * Create a dataset run item
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void datasetRunItemsCreateTest() throws ApiException {
        CreateDatasetRunItemRequest createDatasetRunItemRequest = null;
        DatasetRunItem response = api.datasetRunItemsCreate(createDatasetRunItemRequest);
        // TODO: test validations
    }

}
