/*
 * langfuse
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kuga.langfuse.client.api;

import com.kuga.langfuse.client.invoker.ApiException;
import com.kuga.langfuse.client.model.CreatePromptRequest;
import java.time.OffsetDateTime;
import com.kuga.langfuse.client.model.Prompt;
import com.kuga.langfuse.client.model.PromptMetaListResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PromptsApi
 */
@Disabled
public class PromptsApiTest {

    private final PromptsApi api = new PromptsApi();

    /**
     * Create a new version for the prompt with the given &#x60;name&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void promptsCreateTest() throws ApiException {
        CreatePromptRequest createPromptRequest = null;
        Prompt response = api.promptsCreate(createPromptRequest);
        // TODO: test validations
    }

    /**
     * Get a prompt
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void promptsGetTest() throws ApiException {
        String promptName = null;
        Integer version = null;
        String label = null;
        Prompt response = api.promptsGet(promptName, version, label);
        // TODO: test validations
    }

    /**
     * Get a list of prompt names with versions and labels
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void promptsListTest() throws ApiException {
        String name = null;
        String label = null;
        String tag = null;
        Integer page = null;
        Integer limit = null;
        OffsetDateTime fromUpdatedAt = null;
        OffsetDateTime toUpdatedAt = null;
        PromptMetaListResponse response = api.promptsList(name, label, tag, page, limit, fromUpdatedAt, toUpdatedAt);
        // TODO: test validations
    }

}
