/*
 * langfuse
 * ## Authentication  Authenticate with the API using [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key  ## Exports  - OpenAPI spec: https://cloud.langfuse.com/generated/api/openapi.yml - Postman collection: https://cloud.langfuse.com/generated/postman/collection.json
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.kuga.langfuse.client.api;

import com.kuga.langfuse.client.invoker.ApiException;
import java.time.OffsetDateTime;
import com.kuga.langfuse.client.model.PaginatedSessions;
import com.kuga.langfuse.client.model.SessionWithTraces;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SessionsApi
 */
@Disabled
public class SessionsApiTest {

    private final SessionsApi api = new SessionsApi();

    /**
     * Get a session. Please note that &#x60;traces&#x60; on this endpoint are not paginated, if you plan to fetch large sessions, consider &#x60;GET /api/public/traces?sessionId&#x3D;&lt;sessionId&gt;&#x60;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sessionsGetTest() throws ApiException {
        String sessionId = null;
        SessionWithTraces response = api.sessionsGet(sessionId);
        // TODO: test validations
    }

    /**
     * Get sessions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sessionsListTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        OffsetDateTime fromTimestamp = null;
        OffsetDateTime toTimestamp = null;
        PaginatedSessions response = api.sessionsList(page, limit, fromTimestamp, toTimestamp);
        // TODO: test validations
    }

}
